name: benchmark

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: [self-hosted, bench]
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          target: wasm32v1-none
          toolchain: 1.84.1
      - name: Generate WeightInfo Files
        run: make generate-bifrost-weights
      - name: Commit Automatically
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 🤖 ($WEIGHT) Generate weightInfo files automatically
          file_pattern: runtime/**/*.rs
